package pac.util;

/* Do not edit this file, generated by build_version_info.bash **/
public class SSBuild {
    public static String build_user = "jeikenberry";
    public static String build_time = "Tue Apr 14 17:01:44 EDT 2020";
}
