package pac.util;

/* Do not edit this file, generated by build_version_info.bash **/
public class SSVersion {
  public static String revision = "";
  public static String[] version_info = {"M       pac/agent/CleartrackClassWriter.java",
      "M       pac/agent/CleartrackMain.java", "M       pac/agent/CleartrackVerifier.java",
      "M       pac/agent/hierarchy/ClassHierarchy.java",
      "M       pac/agent/hierarchy/ClassType.java", "M       pac/agent/hierarchy/MethodType.java",
      "M       pac/config/RunChecks.java", "M       pac/inst/taint/SystemInstrumentation.java",
      "?       pac/inst/taint/VMInstrumentation.java", "M       pac/util/SSVersion.java",};
}
